### ISSUE TITLE
"multiplayer" doesn't appears

### ISSUE THREAD

**Issue by diinoft** [rwmt/Multiplayer#105]
When i'm playing and activate the mod, the tab "multiplayer" isn't displayed. What do I do? I have the harmony and i'm in the correct version of the game.

**Comment by Mihokyo** [comment]
Using steam ?

Which releases of game + multiplayer?

Last time i got this, because i was putting mod in ("steamapps\common\RimWorld\Mods") to play offline, and when i was turning online the game was loading both folder ("steamapps\workshop\content\294100") and made corrupt mod

**Comment by notfood** [comment]
Github is for issues. Go to the Discord for mod support. Link is in front page.
