### ISSUE TITLE
Improvement: Forming caravan and trading dialog menu should not be forced onto other players (toggleable option)

### ISSUE THREAD

**Issue by Daimyo21** [rwmt/Multiplayer#108]
Similar to how reforming caravans and trading outside of main settlement works, main-settlement trading and caravan forming should NOT force other players to have to participate. 

It should pause the game as it does now to avoid weird behavior but players should be able to view pawns, quests, possibly build, queue up tasks etc. (if building and queuing up tasks could cause desync while one player is trading, this can be a "use with caution beta feature")

To simplify this, it could be a toggleable option when first hosting the game, something like: "Disable forced in-settlement caravan/trading dialog".

Thank you.

**Comment by Daimyo21** [comment]
It was my understanding that Zetrith was working on adding this feature (Zetrith mentioned it in discord) so I personally stopped working on it. Its been a while since I looked at the code and found a partial work around.

**Comment by SokyranTheDragon** [comment]
Should this be closed? I believe this was implemented with the commit a89a1f05aaa028460302265391067e684993ea40

**Comment by SweptWasTaken** [comment]
> 
> 
> Should this be closed? I believe this was implemented with the commit [a89a1f0](https://github.com/rwmt/Multiplayer/commit/a89a1f05aaa028460302265391067e684993ea40)

Yes.

**Comment by Daimyo21** [comment]
Thanks guys for following up!
