### ISSUE TITLE
Monument desync on "Place blueprint"

### ISSUE THREAD

**Issue by Mihokyo** [rwmt/Multiplayer#110]
Tried on both computer, re-downloading the game, different ressource for the build. 

I'm bit confuse because NotFood say she doesn't have any problem with :/.
But that strange.. Could be one mod i downloaded without activate them ?

The save is fresh and full vanilla, i forced the quest in solo then host the game and accept the quest once i'm in MP with arbiter joined.

Reproduce:
- Accept quest
 - Place the monument and wait for pawn place it
 - Use Blueprint menu and choose ressource
 - Desync happen

• 1 Rimworld version: [1.2.2723 rev661]
• 2 Multiplayer mod version: [0.5.1.8]
• 3 Does the issue/desync happen when only harmony and the mp mod is enabled? [Yes]
• 4 Have you both tried to resubscribe/redownload* the mods?: [Yes]
• 5 Have you both tried to delete the "data" folder found in rimworlds directory and verifed the integrity of the game afterwards?: [Yes]
• 6 Are you all running the same language for rimworld?: [Yes, English]
• 7 
[Desync-03.zip](https://github.com/rwmt/Multiplayer/files/5087425/Desync-03.zip)

**Comment by SweptWasTaken** [comment]
Yep, what'll happen with me when playing is a ton of the blueprints will be "forbidden" and i'll have to cancel the monument and place the blueprints again.
