### ISSUE TITLE
[RW Royalty 1.2.2723 rev661, MP:0.5.1.9999] Bestowal ceremony 

### ISSUE THREAD

**Issue by Mihokyo** [rwmt/Multiplayer#113]
Force bestowal ceremony cause desync.

I know this is a know issue
________________

Report from discord :

With desync trace:
https://discordapp.com/channels/524286515644203028/696348995030614036/742637056848560279

Without trace:
https://discordapp.com/channels/524286515644203028/524286515644203030/745263628223119370
https://discordapp.com/channels/524286515644203028/526116932655775744/745063444717240392
https://discordapp.com/channels/524286515644203028/696348995030614036/742795522125070427
https://discordapp.com/channels/524286515644203028/526116932655775744/740479766024421416

**Comment by ZoeyVS** [comment]
Fixed by NotFood in v0.5.3.0
