### ISSUE TITLE
Desync on Auto-Save

### ISSUE THREAD

**Issue by NotherGithubAccount** [rwmt/Multiplayer#116]
When the host completes an action that changes game data, e.g. adding a task to a workbench or forbidding an item, at the exact same time the save triggers, the game desyncs within a minute after the save. I can not say if this is an issue on the client also. The timing needed is within the milliseconds ballpark, to the user it feels as if the click actually triggered the save.

Now, I realize that this should be a once in a blue moon problem, but this tight timing happens far more often than is statistically probable. While inconsequential clicks, e.g. opening an info window, are not a problem, they too coincide with auto-saves often. Whatever triggers the check if an auto-save is due must be somehow tied to user action (among other things).

Any change made is present in the game after the save, but not in the save itself. I wonder if the action is not communicated to the client(s) or the arbiter due to the save freeze, or if things somehow involve the RNG and are communicated in the wrong order. I will try to verify the status of the action on the client at the next opportunity.

**Comment by SaberShip** [comment]
Can confirm this is still an issue on v0.5.3.0

**Comment by NotherGithubAccount** [comment]
FYI: When I reported this, it happened with two desktop PCs on the same gigabit switch.

Though it was so common, if you haven't noticed it yourself, there must have been other factors at play. Both machines were running Linux. Maybe that or a mod caused it. (Haven't played multiplayer since.)

**Comment by LuzBun** [comment]
> This is due to lag and client computers unable to keep up. Enable pause on autosave and wait a bit before unpausing.

While this solves it for many users, it seems to remain for some to this day.

**Comment by Zetrith** [comment]
Likely to have been fixed as autosaves have been reworked since.
