### ISSUE TITLE
One-keypress wiki update

### ISSUE THREAD

**Issue by Synaps3** [rwmt/Multiplayer#117]
https://github.com/rwmt/Multiplayer/wiki/Async-time

Says "this feature is currently disabled"

We're playing right now and you definitely *can* pause time separately in our two colonies.  

So please just select that "disabled" line and hit delete.  Done.

I'd do it myself but I can't figure out how. I assume the wiki can't be updated except by owners.

**Comment by Zetrith** [comment]
I also had to press my mouse a few times but it's fixed.
