### ISSUE TITLE
Updating to 1.1

### ISSUE THREAD

**Issue by notfood** [rwmt/Multiplayer#12]
Current situation: Multiplayer works with minor issues, ready to ship.

Done...
- `Client/Multiplayer.cs`
  - [x] harmony.DoAllMpPatches() need checking
  - [x] DoPatches() need checking
  - [x] CheckInterfaceVersions() fails with any MPAPI mod user
- `Client/MultiplayerMod.cs`
  - [x] Arbiter doesn't re-launch when rehosting
  - [x] LoadableXmlAssetCtorPatch, xmlAssetHashes has a concurrency issue
- `Client/Designators.cs`
  - [x] Harmony 2.x can't handle some designators patches.
- `Client/MpPatches.cs`
  - [x] MpPatch incompatible with Harmony 2.x
- `Client/ScribeUtils.cs`
  - [x] SaveLoad fails, XmlNodeWriter doesn't exist
  - [x] **Saving doesn't work**
  - [x] Hosting a 2nd time in the same game session crashes
- `Client/Sync/SyncSerialization.cs`
  - [x] Work table bills aren't working
  - [x] Selecting a quest creates a bunch of spam
  - [x] MakeGenericMethod fails under mono 4.7.2
- `Multiplayer.Common.ServerPlayingState`
  - [x] `HandleSelected()` needs to account for 1.1 bigger selection limit.
- `Client/Patches.cs`
  - [x] Drafting colonists and trying to issue orders causes SyncWorker not implemented
  - [x] Colonists unable to drop weapons
  - [x] DLC features need patching (Quests, Powers, etc)
- `Client/Blueprints.cs`
  - [x] Failing transpilers
- Publisher
  - [x] Convert to Task and publish to nuget for easier deployment
- `Client/DebugTools.cs` has been excluded from build
  - [x] Harmony transpilers need recheck
- `Client/Optimizations.cs`
  - [x ] Evaluate if the optimizations are still required
- `Client/ClientNetworking.cs`
  - [x] A white window appears under Windows OS when Arbiter starts

For the future...
- `Synchronization`
  - [x] ~~Consider removing SyncDelegate~~

**Comment by bnelz** [comment]
`string assemblyDir = System.IO.Path.Combine(mod.RootDir, "Assemblies");`

This approach will not work for loading mod assemblies as they may change. 

- [ ] Update assemblyDir to use loaded assembly base directory

**Comment by bnelz** [comment]
I have completed:

```
 WipeExistingThings
 WipeAndRefundExistingThings
 SpawnBuildingAsPossible
```

and

```
 CancelRootPlayStartLongEvents
 Pawn_ApparelTracker
```

Tracked on my fork.

**Comment by bnelz** [comment]
`wip/1.1` branch is now up to date with latest changes and 0 errors in logs at mod load time.

Current issues being tracked:

- [ ] DesignateFinalizer is a workaround for new Harmony related behavior. Validate this fix / update Harmony as we work through the root cause
- [ ] Index OOB exception is being experienced on some platforms related to [https://github.com/rwmt/Multiplayer/blob/master/Source/Client/MultiplayerMod.cs#L231](xmlAssetHashes) `List` size.
```
IndexOutOfRangeException: Index was outside the bounds of the array.
  at System.Collections.Generic.List`1[T].Add (T item) [0x0001e] in <567df3e0919241ba98db88bec4c6696f>:0 
  at Multiplayer.Client.LoadableXmlAssetCtorPatch.Prefix (Verse.LoadableXmlAsset __instance, System.String contents) [0x00012] in <a1d7959033474e598047ff7a7bf83de9>:0 
  at (wrapper dynamic-method) Verse.LoadableXmlAsset.DMD<DMD<.ctor_Patch1>?602321664::.ctor_Patch1>(Verse.LoadableXmlAsset,string,string,string)
  at Verse.DirectXmlLoader+<>c__DisplayClass1_0.<XmlAssetsInModFolder>b__0 (System.Int32 i) [0x00029] in <33b99ab6cf5748ec8fe371b3321b9db6>:0 
  at Verse.GenThreading+<>c__DisplayClass7_1.<ParallelFor>b__0 (System.Object _) [0x0000f] in <33b99ab6cf5748ec8fe371b3321b9db6>:0 
UnityEngine.DebugLogHandler:Internal_LogException(Exception, Object)
UnityEngine.DebugLogHandler:LogException(Exception, Object)
UnityEngine.Logger:LogException(Exception, Object)
UnityEngine.Debug:LogException(Exception)
Verse.<>c__DisplayClass7_1:<ParallelFor>b__0(Object)
System.Threading.QueueUserWorkItemCallback:WaitCallback_Context(Object)
System.Threading.ExecutionContext:RunInternal(ExecutionContext, ContextCallback, Object, Boolean)
System.Threading.ExecutionContext:Run(ExecutionContext, ContextCallback, Object, Boolean)
System.Threading.QueueUserWorkItemCallback:System.Threading.IThreadPoolWorkItem.ExecuteWorkItem()
System.Threading.ThreadPoolWorkQueue:Dispatch()
System.Threading._ThreadPoolWaitCallback:PerformWaitCallback()
```
- [ ] Multiplayer button does not render on Main Menu (@notfood tracking)

**Comment by bnelz** [comment]
Responses to issues around `DesignateFinalizer`. Seems the proper fix will involve writing a new `Transpile` method for subclasses that do not "end with a proper IL code" (those that do not implement a body for `DesignateSingleCell` or `DesignateThing`

![image](https://user-images.githubusercontent.com/1621747/75616500-b30b1200-5b06-11ea-86b9-6290440592be.png)

**Comment by bnelz** [comment]
Opened https://github.com/rwmt/Multiplayer/pull/13 to address public access revocation of Harmony API's `MpPatch` relied on.

**Comment by notfood** [comment]
This is a WIP build, it's for reporting issues. 
[Multiplayer-BROKEN-WIP-1.1-202003012241.zip](https://github.com/rwmt/Multiplayer/files/4273389/Multiplayer-BROKEN-WIP-1.1-202003012241.zip)

**Comment by holmanb** [comment]
@notfood - Would you say that this wip build is ready for testers?

**Comment by notfood** [comment]
You can test, it's not ready for playing a session.

**Comment by Chrometurtle** [comment]
Issues TBob found:

- [ ] Selecting/Deselecting 100+ objects : https://pastebin.com/raw/24pJaPcu
- [ ] Dropping weapon of selected pawn :  https://pastebin.com/raw/gnBUh4Zy
- [ ] Saving doesn't work : https://pastebin.com/raw/8x4bxEuv
- [ ] work table Bills don't work : https://pastebin.com/raw/nresbutt

**Comment by lukaschristmann** [comment]
Fixed the Selection limit in #16

**Comment by DanielHolth** [comment]
@notfood, @bnelz, @lukaschristmann: Leveling up your coding skills and pleasing the community at the same time. Keep up the great work. Respect!

**Comment by rriverak** [comment]
Hey, at the first.. Thanks for this great mod!
I looked at the "Save Problem" and found a Solution that work for me.

Mono need to abstract some OS Functionality for Cross-Plattform.  
In [Xamarin](https://docs.microsoft.com/de-de/xamarin/mac/troubleshooting/troubleshooting#systemnotsupportedexception-no-data-is-available-for-encoding-437) the same "feature" exists.

In this case they try to load external satellite DLL-Files. 
To bring back the Encoding / Decoding we need to provide the follow DLLs.

**Bin-Path**
> /Unity/Hub/Editor/2019.2.17f/Editor/Data/MonoBleedingEdge/lib/mono/gac/

**DLLs**
- I18N.dll
- I18N.West.dll

I copy this 2 DLLs in:

> RimWorld/Mods/Mulitplayer/Assemblies/

Now, i can save my Multiplayer Games...

Loading crashes right after a fresh Save is done. 
I need to restart the complete game to load my Multiplayer-Save-Game, but it loads.

**Comment by notfood** [comment]
Multiplayer 1.1 has been released :tada:
