### ISSUE TITLE
[RW 1.2.2753r715 Royalty 1.2, MP:0.5.2.0] Linux / Windows refuse to connect (End of line encoding difference, unix (LF) / windows (CR LF))

### ISSUE THREAD

**Issue by mjevans** [rwmt/Multiplayer#122]
When the multiplayer mod is comparing configs and ensuring the systems are synchronized it fails to account for differences in line encoding between platforms.

diff -ub shows no difference (-b ignores non-printing characters like line endings), and the difference in file-size also makes a strong case that the only difference is the line endings.

Examining the smaller two files with a hex-view also makes it clear that line endings are the cause of the difference.

543 ./Config/Mod_1127530465_RimatomicsMod.xml
556 ./Windows/Mod_1127530465_RimatomicsMod.xml

5119 ./HugsLib/SpottedMods.xml
5230 ./Windows/SpottedMods.xml

This is where the bug exists

https://github.com/rwmt/Multiplayer/blob/a7e8c8b01237ad570f2088638e3daf777841bc6f/Source/Client/ModManagement.cs#L168

I agree with this stackoverflow example, that a regular expression is the correct answer.

https://stackoverflow.com/a/8196219/825613  ( string result = Regex.Replace(input, @"\r\n?|\n", replacementString); )

I hereby assert that the following is obvious to anyone skilled in the 'art'.  I refuse to attempt to claim any copyright or any other sort of rights in relation to it.  I just want this mod to work.

`var localFileContents = Regex.Replace(File.ReadAllText(localFileName), @"\r\n?|\n", "\n");
`
Additional documentation if necessary:
https://docs.microsoft.com/en-us/dotnet/api/system.text.regularexpressions.regex.replace?view=netcore-3.1#System_Text_RegularExpressions_Regex_Replace_System_String_System_String_System_String_

**Comment by Nebual** [comment]
Nice digging; fixed in v0.5.2.1 which'll go to Workshop this week.
