### ISSUE TITLE
Mod config sync fails when redirecting savedatafolder

### ISSUE THREAD

**Issue by JyeGuru** [rwmt/Multiplayer#126]
When running with a relative config path (for example `"-savedatapath=..\Config") all files fail validation.
![image](https://user-images.githubusercontent.com/5215014/103106598-dfda7800-468a-11eb-8082-02d7de625212.png)
![image](https://user-images.githubusercontent.com/5215014/103106605-e7018600-468a-11eb-947d-e6181b911bf0.png)

Note that the path also seems to be cut off weirdly. If I tell the client to sync, it restarts and no longer shows a conflict. However, it has created a strange folder structure, replicating Client 1's full path under Client 2's folder. Deleting this folder causes the mod sync error to reappear on next connect.
![image](https://user-images.githubusercontent.com/5215014/103106638-38aa1080-468b-11eb-8c2f-5fa2c31ce271.png)

Running the connecting client with the absolute path (eg: `"-savedatapath=D:\Games\Rimworld Multiplayer\Test\Game Client 2\Config"`) still behaves the same, confirming it is a host-side issue.

Running the hosting client with an absolute path, while the connecting client is using a relative path, works fine. This seems to be something in the way the host is providing the config data to the client to compare.

Currently [working around this](https://github.com/JyeGuru/Rimworld-Multiplayer-Package-Generator/blob/master/Source/Scripts/Run.cmd#L20) using Powershell's `Resolve-Path` in my launch script to force absolute paths on launch. In all tests above, the arbiter command line fix (from #124) is running on the host, however the issue can be repeated even without arbiter running.

**Comment by Nebual** [comment]
Thanks for the detailed writeup! In particular, discovering the "imworld" cutoff, and that its host-side, helps narrow it down, putting up a PR shortly and I'll post a Beta build with this fix to the Discord today.
