### ISSUE TITLE
Can't start a new colony after installing this mod

### ISSUE THREAD

**Issue by murad-alm** [rwmt/Multiplayer#130]
After installing the 0.5.1.8 version of the Multiplayer mod i cannot start a new colony any more.
When i click on "New colony" i can choose a scenario but clicking "Next" doesn't do anything.
My game's version is 1.2.2753 and i have following other mods:
Harmony, ModManager, CommonSense, AllowTool, SimpleSidearms, SnapOut, WallLight, WorkTab & PickUpAndHaul.
I am sure this problem is because of the Multiplayer mod as after disabling it the game worked correctly.

Thanks for the support and the help!

**Comment by Shrakna** [comment]
The current version on GitHub is not the most up to date version. (Idk why, It's been brought up) The most current release on Steam is 0.5.2.0. This can be found under Test and Release Builds on the Discord. Or if you somehow just download it from the Steam Workshop. Hope this helps.

**Comment by murad-alm** [comment]
> 
> 
> The current version on GitHub is not the most up to date version. (Idk why, It's been brought up) The most current release on Steam is 0.5.2.0. This can be found under Release and Test Builds on the Discord. Or if you somehow just download it from the Steam Workshop. Hope this helps.
> 
> GitHub version last updated Aug. 8th, 2020. Steam version Sep. 11th, 2020

Hi Sharkna,
Thanks for the reply! would you please be so kind and share the Discord link?

**Comment by Shrakna** [comment]
> > The current version on GitHub is not the most up to date version. (Idk why, It's been brought up) The most current release on Steam is 0.5.2.0. This can be found under Release and Test Builds on the Discord. Or if you somehow just download it from the Steam Workshop. Hope this helps.
> > GitHub version last updated Aug. 8th, 2020. Steam version Sep. 11th, 2020
> 
> Hi Sharkna,
> Thanks for the reply! would you please be so kind and share the Discord link?

You can join the server here. https://discord.gg/S4bxXpv There is also additional info like mod compatibility, which will probably prove useful.

**Comment by murad-alm** [comment]
Thanks! I will try it and close the issue if it works!
Cheers!

**Comment by Shrakna** [comment]
> Thanks! I will try it and close the issue if it works!
> Cheers!

I mean technically if the specific version of the mod that is the only one available on this platform has this issue for you then I don't think your Issue is improper in any way. Perhaps just needs the title changed to reflect it as a GitHub version issue. Have a wonderful day

**Comment by murad-alm** [comment]
> 
> 
> > Thanks! I will try it and close the issue if it works!
> > Cheers!
> 
> I mean technically if the specific version of the mod that is the only one available on this platform has this issue for you then I don't think your Issue is improper in any way. Perhaps just needs the title changed to reflect it as a GitHub version issue. Have a wonderful day

Yes i agree! I think the developers forgot to release the new version on GitHub or maybe it is still under development.
Anyway, your solution worked for me. Thank you very much! I will close the issue here but i hope the developers will notice this on the Discord server.
You too, have a very nice day!
Cheers!
