### ISSUE TITLE
Download out of date

### ISSUE THREAD

**Issue by za3k** [rwmt/Multiplayer#131]
Please add a released version for 1.2. It works on Steam workshop but the download says it's for 1.1 only

**Comment by ranfur8** [comment]
Same please, Upload the 1.2 release version.

**Comment by Nebual** [comment]
I've posted https://github.com/rwmt/Multiplayer/releases/tag/v0.5.2.0 (which is just the current Workshop version from September), hoping to release a v0.5.2.1 shortly.
