### ISSUE TITLE
Syncing the Game Over Window

### ISSUE THREAD

**Issue by Shrakna** [rwmt/Multiplayer#133]
In Singleplayer when everyone dies a "Game Over" window pops up giving the user the option to end the game or continue. 

In Multiplayer this window has been disabled and the game just keeps continuing.  

While this really has no affect on the mod or gameplay it does come into play if you consider compatibility with mods that use and edit that Game Over window. Or if it is written to maybe say something custom. While it is very redundant it is still a Core game feature. 

Picture Here: https://cdn.discordapp.com/attachments/524286515644203030/802827030705733632/unknown.png

**Comment by SweptWasTaken** [comment]
It'll probably be handled on a case by case basis with mods.
