### ISSUE TITLE
Map Errors "Wrong random state on map 0"

### ISSUE THREAD

**Issue by Hollow-HL** [rwmt/Multiplayer#148]
This error occurs when you force a settler to manually start building various furniture, work tables, and more.

I apologize if I made mistakes in the text, I do not know English well.

![2](https://user-images.githubusercontent.com/79443548/108682021-fdf11700-7519-11eb-9ebe-7e8d6c0a8a80.png)
![1](https://user-images.githubusercontent.com/79443548/108682039-047f8e80-751a-11eb-8f16-6d98c2fb484c.png)

**Comment by Shrakna** [comment]
"Wrong Random State on Map 0" just means "Your game has Desynced" It is a generic message. 

Also this is not normal Multiplayer behavior. I recommend deleting your data folder and verifying the files. Please join the discord for better help with troubleshooting. https://discord.gg/wg4k3cyK

**Comment by Hollow-HL** [comment]
can you tell me where this folder is located, or do you mean the entire folder with the game?

**Comment by Shrakna** [comment]
> can you tell me where this folder is located, or do you mean the entire folder with the game?

Here

C:\Program Files (x86)\Steam\steamapps\common\RimWorld\Data

Though a full re-install would do the same I'm sure.

**Comment by ZoeyVS** [comment]
Generic Desync message. Too vague to list as an issue of MP (could just be un-synced mod), as Shrakna said, take it to the Discord.

**Comment by cjsal95** [comment]
I checked the folder located at "C:\Users\USER\AppData\LocalLow\Ludeon Studios\RimWorld by Ludeon Studios\Config" to compare folder structures with other players I'm playing multiplayer with. (Or to check if the contents of each file are the same!)

I replaced both the "ModsConfig.xml" and "Mod_Number_brabra~.xml" files with identical ones.

That's how I resolved it.😀
