### ISSUE TITLE
Add all supported Languages

### ISSUE THREAD

**Issue by CryoRenegade** [rwmt/Multiplayer#15]
- [x] English 
- [x] French
- [x] German
- [x] Polish
- [x] Russian
- [x] Italian
- [x] Spanish - Spain & Mexico
- [x] Czech
- [x] Danish
- [x] Dutch
- [x] Hungarian
- [ ] Japanese
- [ ] Norwegian
- [ ] Portuguese
- [x] Portuguese - Brazil
- [x] Simplified Chinese
- [ ] Swedish
- [x] Traditional Chinese
- [ ] Turkish
- [x] Ukrainian
- [x] Finnish
- [x] Korean
- [ ] Romanian

**Comment by Lecht42** [comment]
I can add Ukrainian, I'm from Ukraine.

**Comment by SweptWasTaken** [comment]
Don't check them off until the pr gets merged.

**Comment by SweptWasTaken** [comment]
#22 and #21 **are confirmed** to be merged so I checked them off. They're just waiting for a certain patch.

**Comment by Lecht42** [comment]
Please change Ukranian to Ukrainian label in the mod language file. We are created new language Ukranian XD.

**Comment by Zetrith** [comment]
Moved to https://github.com/rwmt/Multiplayer-Locale/issues/3
