### ISSUE TITLE
Add mechanism for donation for development

### ISSUE THREAD

**Issue by EmmanuelMess** [rwmt/Multiplayer#151]
You should probably add a Patreon or something :)

**Comment by notfood** [comment]
Several individuals colaborate, there is no RWMT Fundation to account and distribute donations. Money complicates matters... We have no expenses and we aren't hiring anyone, nobody is getting paid. It's best to donate to the individuals or commision. You can find each developer kofi/patreon and more information in the Discord FAQ.
