### ISSUE TITLE
Custom difficulty settings seems to be ignored.

### ISSUE THREAD

**Issue by mightyhuhn** [rwmt/Multiplayer#166]
in multiplayer games the custom difficulty settings seems to be ignored.

the simples to test would be:
"enemy death on downed" 0%
"Food poison chance" 0%
"scaria rot" 0%

even with these setting they still are all are happening.

i'm currently testing this with no other mods applied and will update if needed.

**Comment by Zetrith** [comment]
Fixed in the latest beta. Thanks for reporting.
