### ISSUE TITLE
1.3 compatibility

### ISSUE THREAD

**Issue by kosch104** [rwmt/Multiplayer#171]
Will this project be made compatible with 1.3?

**Comment by SweptWasTaken** [comment]
Yes.

**Comment by kosch104** [comment]
Is there any ETA on when this will be done, is any help required?

**Comment by SweptWasTaken** [comment]
> 
> 
> Is there any ETA on when this will be done?

No.

>Is any help required?

If you're a Rimworld modder and know C# checkout our [dev wiki](https://hackmd.io/Gd_gueokTNui_fqzOSG2Tg#Dev-MP-Wiki).
