### ISSUE TITLE
Assigning medicine in the Assign tag causes a desync

### ISSUE THREAD

**Issue by SweptWasTaken** [rwmt/Multiplayer#177]
Pawns can take medicine into their inventory now.

**Comment by joeecarter** [comment]
I've tried this and picking up medicine seems to work fine. I've tested pawns holding different amount of medicine and also making sure save/reload works.

**Comment by SweptWasTaken** [comment]
> 
> 
> I've tried this and picking up medicine seems to work fine. I've tested pawns holding different amount of medicine and also making sure save/reload works.

Are you testing this with the latest build of the dev-branch Multiplayer mod on 1.3 with Ideology disabled?

**Comment by joeecarter** [comment]
> > I've tried this and picking up medicine seems to work fine. I've tested pawns holding different amount of medicine and also making sure save/reload works.
> 
> Are you testing this with the latest build of the dev-branch Multiplayer mod on 1.3 with Ideology disabled?

Yeah on the development branch mod list is:
- Harmony
- Core
- Royalty
- Multiplayer

**Comment by SweptWasTaken** [comment]
Well I just tested this without Royalty and I get a desync the second I try to assign medicine to people. Are you sure you're making them pick it up through the "Assign" tab?

**Comment by joeecarter** [comment]
> Well I just tested this without Royalty and I get a desync the second I try to assign medicine to people. Are you sure you're making them pick it up through the "Assign" tab?

Nope I was just testing the wrong thing! Replicated it now

**Comment by SweptWasTaken** [comment]
@joeecarter Sokryan has a fix for this already so I unassigned you.
