### ISSUE TITLE
Add a native ping tool

### ISSUE THREAD

**Issue by SweptWasTaken** [rwmt/Multiplayer#196]
[Dubs Mint Minimap](https://github.com/Dubwise56/Dubs-Mint-Minimap) has a ping tool for multiplayer integrated into the mod, but we don't have a native ping tool for Multiplayer. 

In vanilla Multiplayer i'd like this to be a hotkey and/or additional tool in the bottom right bar that would mark an area for your multiplayer companions. The ping would either create an alert in the top left or bottom right alert area that you would be able to click on and teleport your camera directly to the ping location.

**Comment by Zetrith** [comment]
Any suggestion for what the key should be?

**Comment by LuzBun** [comment]
Mouse 3 if that's free would be handy. (Or M5 if you want to support mice with extra buttons)

**Comment by SokyranTheDragon** [comment]
As a personal opinion, I'd like an option to do a button+mouse combo (something like shift+LMB). This could potentially allow for different types of pings, if we ever decide to go that route, with different buttons having different effects.

And speaking of different types of pings: one thing I see so far would be pinging a specific place (the most basic one), or pinging a specific Thing (like, a pawn, or maybe a building) and have the ping follow it around.

**Comment by LuzBun** [comment]
Modifiers on the ping could be of great use and expand further than Minimap ever did. Could see this being very handy in games where people can't talk or don't want to.

**Comment by SweptWasTaken** [comment]
Modifiers would be unnecessary bloat. A simple ping will suffice. Binding it to a button + mouse combo is a good idea.

**Comment by victordlp8** [comment]
When I think of a ping tool for rimworld, I think of doing Ctrl + Alt + M3 and a dial appears with all the ping modes, then with the mouse you select one (attack ping, defense ping, build ping, haul ping and normal ping are the basics) and then Alt + M3 wherever you want on the map.

- Each ping may or may not have the same sound but they should definitely have different visuals on the screen.
- They must be able to see or know where they are with any zoom, I think that they are enlarged and reduced according to the zoom is appropriate.
- If it does not come within the field of view, an arrow may appear in the direction of the ping.
- If the ping is done in another tile on the world, a small event or something like that should appear on the right.

These are the things that my ideal ping tool should have, it is just a suggestion. Thanks.

**Comment by SweptWasTaken** [comment]
> 
> 
> When I think of a ping tool for rimworld, I think of doing Ctrl + Alt + M3 and a dial appears with all the ping modes, then with the mouse you select one (attack ping, defense ping, build ping, haul ping and normal ping are the basics) and then Alt + M3 wherever you want on the map.
> 
>     * Each ping may or may not have the same sound but they should definitely have different visuals on the screen.
> 
>     * They must be able to see or know where they are with any zoom, I think that they are enlarged and reduced according to the zoom is appropriate.
> 
>     * If it does not come within the field of view, an arrow may appear in the direction of the ping.
> 
>     * If the ping is done in another tile on the world, a small event or something like that should appear on the right.
> 
> 
> These are the things that my ideal ping tool should have, it is just a suggestion. Thanks.

Again, overly complicated.

I think the idea about the alert for stuff on the world map and the arrow for a ping on the main colony view is great and was my central idea for this mechanic.

**Comment by LuzBun** [comment]
These are just additional options, the main ping would come first. Optional others alike apex. They won't be seen if not used so there's no bloat for users.
