### ISSUE TITLE
Using Preach Health ability causes Null

### ISSUE THREAD

**Issue by TheCoolestPaul** [rwmt/Multiplayer#201]
I am running on the latest  build of the development branch, Rimworld 1.3 with Royalty & Ideology.

Step to recreate
1. Rescue a pawn to a medical bed.
2. Get another pawn to cast the ability "Preach Health".
3. [See error](https://pastebin.com/naUzFsYH)

**Comment by Zetrith** [comment]
Can't reproduce. Did you test the steps on a fresh world with debug tools?

**Comment by TheCoolestPaul** [comment]
I just started a fresh save, with one other player. This time the pawn wasn't even in a medical bed they were just standing in a room.

**Comment by Zetrith** [comment]
Thanks for reporting. The missing piece of information was that the ability comes from an Ideology role.
