### ISSUE TITLE
Error when changing growing zone crop

### ISSUE THREAD

**Issue by TheCoolestPaul** [rwmt/Multiplayer#204]
### Rimworld Version 1.3, Royalty & Ideology

Steps to reproduce

1. Either the host OR any clients place a grow zone down.
2. Either the host OR any clients try to change the crops to be grown.

I have tested this on multiple fresh saves. This error happens regardless of who places the grow zone and who changes the crop.
[Pastebin Error](https://pastebin.com/JfEnjHBL)

**Comment by TheCoolestPaul** [comment]
I have tested this some more and we still get the error even if it's only the host and no other clients connected.

**Comment by Zetrith** [comment]
Thanks for the report.
