### ISSUE TITLE
"Soft" Desync regarding name of colonist generated in raid

### ISSUE THREAD

**Issue by FatCat1978** [rwmt/Multiplayer#208]
For host, it was generated as "Micheal Fryer", player two had it generate as "Pascal Pye Roy". Stats, Bio, and Health tab generated the exact same, and stayed consistent. No Desync error was brought up - we just noticed this on the fly.

**Comment by LuzBun** [comment]
Known issue to effect raids, traders and alike. This is harmless as current and will fix when client rejoins.

**Comment by SokyranTheDragon** [comment]
Honestly, I'm kinda surprised this issue wasn't mentioned here yet. I saw it mentioned on Discord multiple times, but not here. Do we have any more known issues that aren't listed on Github?

**Comment by Shrakna** [comment]
> Honestly, I'm kinda surprised this issue wasn't mentioned here yet. I saw it mentioned on Discord multiple times, but not here. Do we have any more known issues that aren't listed on Github?

There are a few. Some regarding Royalty, some Async. There are a couple I would say maybe aren’t a solid issue, but more of a feeing something is maybe not right. (Preferred Player Characters) 

The HubsLib config issue, etc. Probably should be listed here for folks who don’t use the Discord. imo

**Comment by SweptWasTaken** [comment]
> 
> 
> Honestly, I'm kinda surprised this issue wasn't mentioned here yet. I saw it mentioned on Discord multiple times, but not here. Do we have any more known issues that aren't listed on Github?

I was frustrated about this too, going through and adding all these was on my todo list.
