### ISSUE TITLE
Stockpiles unconfigurable

### ISSUE THREAD

**Issue by rmwiesenberg** [rwmt/Multiplayer#212]
Unable to configure stockpiles in MP beta c66f148.
Menu opens but checkboxes are cannot be toggled.
Relatively new replay (< 2 days).
[Player3082's game.zip](https://github.com/rwmt/Multiplayer/files/6910564/Player3082.s.game.zip)

**Comment by Thomas107500** [comment]
if i remember correctly c66f148 isnt the latest one, make sure to read the channel pins

**Comment by LuzBun** [comment]
> if i remember correctly [c66f148](https://github.com/rwmt/Multiplayer/commit/c66f148457d4a9c9ff0f1372c66072fb63befb22) isnt the latest one, make sure to read the discord channel pins

It is, released in release-and-test-builds, the beta.

**Comment by Thomas107500** [comment]
on wait nvm you mean the beta one, sorry for that

**Comment by SweptWasTaken** [comment]
c66f148 is the latest commit on development branch.

**Comment by SweptWasTaken** [comment]
> 
> 
> Unable to configure stockpiles in MP beta [c66f148](https://github.com/rwmt/Multiplayer/commit/c66f148457d4a9c9ff0f1372c66072fb63befb22).
> Menu opens but checkboxes are cannot be toggled.
> Relatively new replay (< 2 days).
> [Player3082's game.zip](https://github.com/rwmt/Multiplayer/files/6910564/Player3082.s.game.zip)

Replicated on my own save and a new safe created on current commit. Looks like this is worse than the older one as no checkboxes can be toggled, and clear all/allow all won't work.
![2021-07-30_22-00-01](https://user-images.githubusercontent.com/49448379/127729253-66b271be-9073-4c42-96ac-fe8f3bd5708b.gif)

**Comment by SweptWasTaken** [comment]
Fixed for me on latest commit, uploading to releases now.
