### ISSUE TITLE
prisoner menu disappears by trying to convert

### ISSUE THREAD

**Issue by Djiriod** [rwmt/Multiplayer#213]
The menu to convert / get them as colonist / reduce resistance / etc will disappers when trying to convert them.
The person who clicked on convert will still see the menu, untill they have to rejoin the game.

**Comment by Djiriod** [comment]
![](https://cdn.discordapp.com/attachments/526116932655775744/871047199470018560/unknown.png)

**Comment by SweptWasTaken** [comment]
Can anyone replicate this?

**Comment by SweptWasTaken** [comment]
Fixed by dbf27e9 I believe.
