### ISSUE TITLE
CTD + Desync Form Caravan

### ISSUE THREAD

**Issue by Shrakna** [rwmt/Multiplayer#214]
**Rimworld version: 1.3.3076
Mp version: BETA fcac8ac** 

Issue: When following these steps the Host will crash to desktop (I have no logs generated for this apologies) The Client will also Desync. While these exact steps would be a very niche bug I do wonder if this points to maybe an underlying issue somewhere in either, Abandoning or Settling a tile, or Forming a caravan. 

(Was trying to test out the "Settling on a raided/abandoned tile desyncs. (Don't do that)" known issue from the Discord)

I have deleted core and validated my files. I have redownloaded the beta. I have reproduced 3 times. 

1. Start game
2. Form Caravan
3. Abandon tile
4. Start MP Server
5. Once Client joins Settle new tile
6. Form Caravan and try to send them on their way.
At this point Client desyncs and Host crashes

**Comment by Shrakna** [comment]
Trying to test something else out and the issue seems to be Form Caravan on the world screen. As I've just crashed again whilst trying to form one.

**Comment by Zetrith** [comment]
Can't reproduce. Do you have any mods running? Could you include host's log file?

**Comment by Shrakna** [comment]
Updated to the latest Beta (BETA 0d19357 for Rimworld 1.3.3076) to test this again and it is no longer an issue. Something must have fixed it! Thanks
