### ISSUE TITLE
Unable to edit storage filters

### ISSUE THREAD

**Issue by alinutu1** [rwmt/Multiplayer#226]
During multiplayer when i wanted to create a fridge i stuck a problem where i couldn't edit the filters in the storage
i decided to go to singleplayer to do this and it still didn't work
then i tried shuffling mods one by one until i realized it's caused by the multiplayer mod

https://user-images.githubusercontent.com/88349414/127924175-2ad2e4ba-371b-4444-91cb-ad0fb7053f96.mp4

**Comment by SweptWasTaken** [comment]
You appear to be a couple of versions behind.

**Comment by SweptWasTaken** [comment]
Cannot replicate on latest commit of development, closing.
