### ISSUE TITLE
Publicize/Publicise Command Not Found

### ISSUE THREAD

**Issue by DarkWugWug** [rwmt/Multiplayer#24]
I was trying to get the project setup to poke around and see what I could help with, but ran into an issue with the Publicise tool used to build `Assembly-CSharp_public`. 
## What I was doing
I was following the setup steps [from the hackmd book](https://hackmd.io/Gd_gueokTNui_fqzOSG2Tg#Compiling). 
## What I expected
The project to build successfully
## What happened
```
1>------ Rebuild All started: Project: MultiplayerAPI, Configuration: Debug Any CPU ------
1>  MultiplayerAPI -> E:\Steam\steamapps\common\RimWorld\Mods\Multiplayer\Assemblies\0MultiplayerAPI.dll
2>------ Rebuild All started: Project: Multiplayer, Configuration: Debug Any CPU ------
2>  '"E:\Steam\steamapps\common\RimWorld\Mods\Multiplayer\Source\..\Publicise\Publicise.exe"' is not recognized as an internal or external command,
2>  operable program or batch file.
2>C:\Program Files (x86)\Microsoft Visual Studio\2019\Community\MSBuild\Current\Bin\Microsoft.Common.CurrentVersion.targets(1328,5): error MSB3073: The command ""E:\Steam\steamapps\common\RimWorld\Mods\Multiplayer\Source\..\Publicise\Publicise.exe" "E:\Steam\steamapps\common\RimWorld\Mods\Multiplayer\Source\..\..\..\RimWorldWin64_Data\Managed\Assembly-CSharp.dll" "E:\Steam\steamapps\common\RimWorld\Mods\Multiplayer\Source\..\Publicise"" exited with code 9009.
========== Rebuild All: 1 succeeded, 1 failed, 0 skipped ==========
```
## What I suggest
I got the project to build using the Publicize tool from the repo https://github.com/jacobEAdamson/publicize. With a little renaming and moving the tool into the folder expected I got the project to build.

1. Shouldn't this tool be provided in this repo?
2. If not, could it be documented as a step in the book?

**Comment by lukaschristmann** [comment]
Which branch were you on?
in the wip-1.1 it should be integrated so you don't need to do anything except clicking build, the project file defines downloading, unzipping and execution of an appropriate release...

If you are on a branch where this is already integrated:
- Which platform are you on?
- Which IDE do you use?

**Comment by DarkWugWug** [comment]
I was on branch master.

Just tested with branch wip-1.1 and it works as expected. I'll go ahead and close this issue.
