### ISSUE TITLE
Cannot administer smoke leaf joints

### ISSUE THREAD

**Issue by sbacklund2013** [rwmt/Multiplayer#240]
The option to administer smoke leaf joints does not result in any action.  Able to click it, but nothing is queued.

**Comment by sbacklund2013** [comment]
The host cannot administer either

**Comment by FelicityBirdsong** [comment]
I had this issue last night with a prisoner. Tried my machine and the host tried as well, but same issue where nothing was queued after clicking on the option. No error message, and didn't cause a desynch either.

**Comment by Zetrith** [comment]
Are you using any mods besides Multiplayer? Also, could you post a screenshot of the UI element which fails to work?

**Comment by FelicityBirdsong** [comment]
![image](https://user-images.githubusercontent.com/88950768/129462478-3970e232-ab9b-4b57-8400-a23b4c0c10f3.png)

That's the screenshot of the mods we're using and I'll see if we can get one of the UI in a sec here.

**Comment by FelicityBirdsong** [comment]
![image](https://user-images.githubusercontent.com/88950768/129462528-81f7b714-21a4-4a5d-9340-a0a30e944232.png)

Go to a pawn, then the Health tab, then Operations, then click 'Administer Smokeleaf Joint'

**Comment by sbacklund2013** [comment]
![image](https://user-images.githubusercontent.com/23019830/129489148-86d99a7f-75e2-41e0-9f41-06b774bc7e9c.png)
Here is my mod list and yes I was referring to the instructions above (pawn->health->operations->add bill->administer joint)

**Comment by FelicityBirdsong** [comment]
Issue happens with attempting to administer ambrosia as well.

**Comment by Zetrith** [comment]
Fixed in the latest beta. Thanks for reporting.

**Comment by sbacklund2013** [comment]
Thank you for a truly spectacular mod

**Comment by FelicityBirdsong** [comment]
Thank you! Looking forward to testing it out. : J
