### ISSUE TITLE
Changing crop on growing zone doesn't update for other players

### ISSUE THREAD

**Issue by Joery** [rwmt/Multiplayer#244]
When changing the crop in a growing zone, it isn't updated for the other player, both for the host if the client changes it and vice versa. When a pawn is planting the crop, it causes a desync after.

**Modlist**
Harmony
Core
Royalty
Ideology
Multiplayer

Using latest non-beta RimWorld with latest GitHub Multiplayer build.
[Desync-01.zip](https://github.com/rwmt/Multiplayer/files/7001665/Desync-01.zip)

**Comment by notfood** [comment]
Schrodinger's issue, I managed to reproduce it earlier but then it worked fine. I removed my commit. It appears to work fine under latest development per da3241ab6d0f2aaf57404f6be6b59b774c8ea1f6, wait for a new test release and try again.

**Comment by Joery** [comment]
We tried with a clean da3241a yesterday, will try again tonight/tomorrow to check

**Comment by Joery** [comment]
Tested with both da3241a & 728728c but with both the same problem. Could you make a build with the commit you removed? I can try with that to see if it works.

**Comment by notfood** [comment]
Mine definitely works but Zetrith used a different method. I find it strange that it's not working for you since your setup is pure vanilla.

**Comment by Zetrith** [comment]
Any errors in the log file on host or client?

**Comment by Joery** [comment]
Yeah, it seems to be Schrödinger's issue, with no mods besides Multiplayer, it works now. When adding a bunch of mods, including Dubs Mint Menu's, it doesn't update. However, no desyncs any more, the chosen plant on the client's side seems to be completely ignored unless the client forces a pawn to sow the area.

Might be something visual after all, will report to Dubs.
