### ISSUE TITLE
Cannot change settings storage\trash 

### ISSUE THREAD

**Issue by Banan1447** [rwmt/Multiplayer#245]
when i try to change some value in game in ui like
![image](https://user-images.githubusercontent.com/37272362/129938503-779e7a41-804d-4170-b48d-8208e359a9e0.png)
here

then just debug menu like 
"Mouse position stack is not empty. There were more calls to BeginScrollView than EndScrollView. Fixing.
UnityEngine.StackTraceUtility:ExtractStackTrace ()
Verse.Log:Error (string)
Verse.Widgets:EnsureMousePositionStackEmpty ()
(wrapper dynamic-method) Verse.Root:Verse.Root.Update_Patch1 (Verse.Root)
Verse.Root_Play:Update ()"

does any solution of fixing it?

**Comment by notfood** [comment]
Is this vanilla? That error comes when it previously erroed. Post the whole log.

**Comment by Banan1447** [comment]
this is build from "https://freetp.org/po-seti/4631-rim-world-po-seti-i-internetu-lan-online-city.html"
if i played with friend just nothing changes 
if i played solo but with mods
[trace.txt](https://github.com/rwmt/Multiplayer/files/7009307/trace.txt)

![image](https://user-images.githubusercontent.com/37272362/129950816-5189ddf4-49e0-456b-9123-1845f0b6bdcf.png)
if u want i can capture this moment and show u

**Comment by Zetrith** [comment]
You are using an outdated version of Multiplayer. Latest beta downloads are available on our Discord. You can also compile the development branch yourself.
