### ISSUE TITLE
Extra Details on Incompatibilities with Better Pawn Control

### ISSUE THREAD

**Issue by techsavvy531** [rwmt/Multiplayer#246]
I know it's already stated that Better Pawn Control has major issues, such as the emergency button causing desync. I just thought I would provide some extra info that anytime the host accessed a tab for which Better Pawn Control manages (e.g. Work, Schedule, Animals, etc.), the client would desync immediately, every time.

**Comment by notfood** [comment]
Multiplayer Compatibility project deals with other mods. Multiplayer targets vanilla.

Also, this is information for the spreadsheet. We have a form in the Discord (channel #mod-report-1-2 ) where you can submit mod related reports.
