### ISSUE TITLE
Mod broken on new update 1.3.3117

### ISSUE THREAD

**Issue by RomanovX** [rwmt/Multiplayer#258]
With the new update to Rimworld (base game only), the mod no longer loads correctly.

![image](https://user-images.githubusercontent.com/6672813/133081100-fee6f981-acf3-4bf5-8ded-1d0e5180c9d2.png)

Reproduction steps:
- Install Rimworld 1.3.3117 (base game only)
- Install Multiplayer mod from latest release
- Install Harmony dependency from workshop
- Auto sort mods (no other mods installed)

**Comment by Zetrith** [comment]
It looks like you aren't on the latest beta.

**Comment by RomanovX** [comment]
My bad, I hadn't checked discord in between
