### ISSUE TITLE
Desync On Change Grow Zone Crop

### ISSUE THREAD

**Issue by soda5** [rwmt/Multiplayer#259]
Sometimes when the user changes the crop that should be grown on a grow zone, the game desyncs. Happens only with some grow zones, but with those it is reproducable. Seems not to be a problem for all zones, even if they are next to each other.

Happens with 0.6.0.3

**Comment by notfood** [comment]
Are you using DubsMint Menus?

**Comment by soda5** [comment]
That ist exactly the case, so that's why I presume?

Is there a list for mod compability or non-compability?

Should I delete this issue?

**Comment by notfood** [comment]
Yeah. Mint Menus needs to be updated.
