### ISSUE TITLE
Desync with error code: wrong random state on map 0

### ISSUE THREAD

**Issue by FaulerMusket** [rwmt/Multiplayer#297]
Get error "random state on map 0" every time after 30 min playing. 

Rimworld version - 1.3.3209 rev891

Mod version - 0.6.1.0. 

all latest desync:

[Desync-42.zip](https://github.com/rwmt/Multiplayer/files/8282087/Desync-42.zip)
[Desync-36.zip](https://github.com/rwmt/Multiplayer/files/8282091/Desync-36.zip)
[Desync-37.zip](https://github.com/rwmt/Multiplayer/files/8282092/Desync-37.zip)
[Desync-38.zip](https://github.com/rwmt/Multiplayer/files/8282093/Desync-38.zip)
[Desync-39.zip](https://github.com/rwmt/Multiplayer/files/8282094/Desync-39.zip)
[Desync-43.zip](https://github.com/rwmt/Multiplayer/files/8282088/Desync-43.zip)
[Desync-34.zip](https://github.com/rwmt/Multiplayer/files/8282089/Desync-34.zip)
[Desync-35.zip](https://github.com/rwmt/Multiplayer/files/8282090/Desync-35.zip)
[Desync-40.zip](https://github.com/rwmt/Multiplayer/files/8282085/Desync-40.zip)
[Desync-41.zip](https://github.com/rwmt/Multiplayer/files/8282086/Desync-41.zip)

Help pls!

**Comment by notfood** [comment]
Github is for bugs. In Discord there is a faq and troubleshooting channel.
