### ISSUE TITLE
Git version does not work with 1.3.3326

### ISSUE THREAD

**Issue by ebrasca** [rwmt/Multiplayer#299]
Harmony from git + Multiplayer from the workshop does work!
Harmony from git + Multiplayer from git does not work!

**Comment by notfood** [comment]
"Does not work" is not a proper bug report. Logs needed.

**Comment by ebrasca** [comment]
I can't find any more info
![2022-05-31-143533_1920x1080_scrot](https://user-images.githubusercontent.com/3901079/171176703-cd6ca934-54c7-429f-afb0-eef8d03b97e3.png)
![2022-05-31-144827_1920x1080_scrot](https://user-images.githubusercontent.com/3901079/171176996-f9b11f8e-c14f-46ca-aaf6-fce700e1e5fa.png)

**Comment by MaximilianSeewald** [comment]
Just press on the red "X" and everything should work

**Comment by ebrasca** [comment]
> 

Have you read what is the problem?

**Comment by ebrasca** [comment]
Where is the multiplayer button then?

**Comment by notfood** [comment]
I suspect you downloaded the repository instead of the release, the repository doesn't include several libraries that become available only after building.

**Comment by ebrasca** [comment]
Thank you!
