### ISSUE TITLE
"Research complete" popup blocks resync popup buttons

### ISSUE THREAD

**Issue by magneticflux-** [rwmt/Multiplayer#301]
Desyncing just after completing research requires closing the entire game because the buttons are blocked. `Esc` and the visible sides of the buttons do not work.

![image](https://user-images.githubusercontent.com/9124288/170920626-93953e9e-b2c5-4c05-a94a-96836390a5a1.png)

**Comment by 20k** [comment]
This also occurs with hospitality, when guests request entry. The easiest way to work around this is for the server to rehost, as that'll force you to disconnect - so no restart required at least
