### ISSUE TITLE
Hash_Diff Error

### ISSUE THREAD

**Issue by MarioCraftLP** [rwmt/Multiplayer#302]
I am trying to play with my friend and I tried our modpack local (i started rimworld 2 times and connected) and it worked like this. But when my friend tries to connect, I get this error, but it says that everything is fine.
![Screenshot 2022-06-03 135814](https://user-images.githubusercontent.com/75859777/171849701-cc24d87d-7b7a-40a3-9d6f-6a2c90780149.png)

**Comment by notfood** [comment]
Probably they have different mod versions. Anyhow, for support head to the Discord. Github is for code issues.
