### ISSUE TITLE
Public execution causes desync

### ISSUE THREAD

**Issue by FSanta** [rwmt/Multiplayer#306]
As soon as the public execution dialog is opened, remote clients desync.

Playing with:
Harmony
Core
Royalty
Ideology
Multiplayer
HugsLib
Stack XXL
CM Color Coded Mood Bar [1.1+]

Thank you for any help!

**Comment by SokyranTheDragon** [comment]
I think I see where the issue may lay. Seems that execution is using `PreceptComp_UnwillingToDo_Chance`, which is using RNG inside of the `Dialog_BeginRitual`. Seems it will need to become seeded. Looking into it right now.

I believe patching the constructor for `Dialog_BeginRitual` should be the way to handle this, as other mods may possibly use RNG inside of their PreceptComps - which is what may be happening with Alpha Memes and the funerals it added (just a speculation here).

**Comment by SokyranTheDragon** [comment]
More info - this only happens if any valid pawn has any of those 2 precepts:

Marriage name: Always woman's
Marriage name: Always man's
