### ISSUE TITLE
Child reaching age 3 creates popup and freezes the game

### ISSUE THREAD

**Issue by SergeantToni** [rwmt/Multiplayer#348]
When a child comes of age 3 a popup appears. ![image](https://user-images.githubusercontent.com/31221046/201445824-dfcab3ca-b3af-47c4-917f-be1d2c36c8f9.png)

The game would lock up (Notification would lock up and seize the UI).

The issue can be ignored by making the host convert to a single-player save to give the settlement a name (By opening the world screen to get the prompt). 

After that it worked again and child related events seem to work fine.

**Comment by MarisKori** [comment]
I confirm, the first child locks the game, the second doesn't.

**Comment by icannotfly** [comment]
i'm seeing the same issue here.
there doesn't seem to be anything in player.log since it crashes the whole game, so i've attached a savefile where a child will turn 3 at 1700 ingame.
[child-crash.zip](https://github.com/rwmt/Multiplayer/files/10007889/child-crash.zip)

**Comment by Feliphysics** [comment]
Looks like, at least on that save, that colony time and map time are out of sync (map is 6 hours ahead), and converting to sp then back to mp fixes that and prevents the issue with the age 3 event

**Comment by icannotfly** [comment]
> Looks like, at least on that save, that colony time and world time are out of sync (world is 6 hours ahead), and converting to sp then back to mp fixes that and prevents the issue with the age 3 event

didn't even realize the time could be different between those two. how does that happen? how do i prevent it?

interestingly, when i converted to SP to try @SergeantToni's fix (which works, by the way), the child growth message didn't pop up until about 2400, when I was expecting it at 1700. that lines up just about perfectly with those six hours.

**Comment by Feliphysics** [comment]
I think there is still no clear explanation as to why the time difference happens, so my best advice would be to keep an eye on it and, if needed (aka, if there is a difference and you are encountering issues, not just because of the difference) convert back to sp and to mp again. Though, if it happens again and you still have the save files from not too long before then feel free to send them, they might be useful

**Comment by MarisKori** [comment]
Time difference increases over time.
~ 5 game hours per 1 game year.

**Comment by Feliphysics** [comment]
I forgot to add that we think we found and fixed the issue, for now to avoid it you can either disable the pause on letter feature or go on discord and grab the latest mp beta, let us know if after that the time gets out of sync again.

(to be clear, to resync time you will still need to convert to sp and back to mp, this only prevents it from happening again)

**Comment by Zetrith** [comment]
Fixed in 0be4a35
