### ISSUE TITLE
Caravan Hitching spot - Form Caravan gyzmo not synced

### ISSUE THREAD

**Issue by Feliphysics** [rwmt/Multiplayer#370]
Tested on the latest stable version of Rimworld (1.4.3641) on both multiplayer 0.7.2 and 0.7.3, no difference between the two.

Forming a caravan through the caravan hitching spot is not synced, so the game doesn't get paused, and the caravan formation window is only created for the client that interacts with the gyzmo. Once the caravan is confirmed and starts forming, the game desyncs.

Minor issue, but probably accounts for a portion of the "caravan desyncs in vanilla" reports.

[Desync-CaravanSpot.zip](https://github.com/rwmt/Multiplayer/files/10784875/Desync-CaravanSpot.zip)

**Comment by Zetrith** [comment]
#366 fixes it I think
