### ISSUE TITLE
Beta and non Beta! Ejecting a Gene through the Gene Assambler not synced!

### ISSUE THREAD

**Issue by sg1aprophis** [rwmt/Multiplayer#373]
Ejecting a Gene from a Gane Bank through the Gene Assambler always Desyncs the Game

1. Open the Gene Assembler
2. Right click a Gene
3. Select: Eject the Gene from Gene Bank
4. Desync

Logs can be found in these Reports!

https://discord.com/channels/524286515644203028/1078715307130105986
https://discord.com/channels/524286515644203028/1043061730177187861

**Comment by SokyranTheDragon** [comment]
Outdated issue, was fixed by #374
