### ISSUE TITLE
Vanilla Multiplayer desync every few seconds to minutes

### ISSUE THREAD

**Issue by Antimate1** [rwmt/Multiplayer#380]
I was told in the discord to make a Issue here. 
Link to discord issue: https://discord.com/channels/524286515644203028/1084124461147631718

I am playing multiplayer with 1 other person, totally vanilla.  We are getting desyncs sometimes every 5 minutes and sometimes every few seconds after resync. There are two different error messages that we get.

1: "wrong random state on map 0"
2: "Trace hashes don't match"

Both seem to me to happen at random. The time of day doesn't matter and  if the pawns do anything or not.

All attempts to fix the issue (you can read all the attempts tried in the discord post) failed. 

Attachted are the latest desync-files and the save game.

[Desync-42.zip](https://github.com/rwmt/Multiplayer/files/10948854/Desync-42.zip)
[Desync-43.zip](https://github.com/rwmt/Multiplayer/files/10948855/Desync-43.zip)
[Desync-44.zip](https://github.com/rwmt/Multiplayer/files/10948856/Desync-44.zip)
[Desync-45.zip](https://github.com/rwmt/Multiplayer/files/10948857/Desync-45.zip)
[Desync-46.zip](https://github.com/rwmt/Multiplayer/files/10948862/Desync-46.zip)
[Antimate's game.zip](https://github.com/rwmt/Multiplayer/files/10948859/Antimate.s.game.zip)

**Comment by KweezyCode** [comment]
same

**Comment by jamesbrady226** [comment]
yeah unfortunately I just don't think this mod works atm

**Comment by Zetrith** [comment]
Update 0.9.4 should be an improvement
