### ISSUE TITLE
Lost Tribe scenario please

### ISSUE THREAD

**Issue by fovarit38** [rwmt/Multiplayer#400]
I would be grateful if you can provide a compiled version with these parameters

\Source\Client\Factions\FactionSidebar.cs 
    private static string scenario = "LostTribe";  #line 17 old Crashlanded
    
    
\Source\Client\Factions\FactionCreator.cs

  var newFaction = NewFaction(
      newFactionID,
      factionName,
      FactionDefOf.PlayerTribe, #line 40  old  FactionDefOf.PlayerColony
      chooseIdeoInfo
  );
            
            
  public static void SetGameInitData()
    {
        Current.Game.InitData = new GameInitData
        {
            startingPawnCount = 5, # line 133 old 3
            gameToLoad = "dummy" // Prevent special calculation path in GenTicks.TicksAbs
        };
    }
    
    
   
    I want to play LostTribe mode, but unfortunately I can't make these changes to the source code myself

**Comment by fovarit38** [comment]
the issues is closed, I have already done it myself.

**Comment by Monkstar** [comment]
I also need this fix. And I can't do it myself actually.
