### ISSUE TITLE
Does not work with unstable version 1.5.

### ISSUE THREAD

**Issue by fdg0** [rwmt/Multiplayer#427]
I know this is completely normal, but I believe this to find out sooner when the solution is available. 
Thank you and you do tremendous work

**Comment by fdg0** [comment]
Will we see it compatible for this unstable version, or wait for the stable version to come out?

**Comment by notfood** [comment]
Please patience. It'll come in time. There will be a proper issue tracking what needs to be done that you can follow, thanks for your support.
