### ISSUE TITLE
Bioferite harvesters cause desync

### ISSUE THREAD

**Issue by twothe** [rwmt/Multiplayer#447]
If Bioferite Harvesters are full, they will cause a desync when trying to give a job to clear it. This can be avoided by disabling automatic extracting and by emptying them manually.

**Comment by DwlufveX** [comment]
Yes, I'm also having this issue, in the case of having Bioferite Harvesters in both worlds, the time starts to be out of sync, tried turning off auto-harvesting, but it still doesn't work, please fix it in time！thanks！

**Comment by SokyranTheDragon** [comment]
Any more info? I've just tried it myself and it seemed to work fine on my end.

**Comment by Spodi** [comment]
I suspect the the holding plattform / harvester too. Current save desyncs as soon as I join. Here are the last few log sadly I wasn't host, but maybe it helps too.
[Desync-253.zip](https://github.com/rwmt/Multiplayer/files/15082638/Desync-253.zip)
[Desync-252.zip](https://github.com/rwmt/Multiplayer/files/15082639/Desync-252.zip)
[Desync-255.zip](https://github.com/rwmt/Multiplayer/files/15082640/Desync-255.zip)
[Desync-254.zip](https://github.com/rwmt/Multiplayer/files/15082641/Desync-254.zip)

**Comment by twothe** [comment]
> Any more info? I've just tried it myself and it seemed to work fine on my end.

I am not perfectly sure, but it feels like it needs a few more holding cells + harvester. We didn't initially have an issue, however later when we had like 10 entities captured it was a guaranteed desync every single time.

**Comment by twothe** [comment]
I have the same 100% desync on capture issue, however I think it is helpful for the devs if there is one issue per issue. Otherwise they have to search through all the issues to find them.
