### ISSUE TITLE
Caravan disappears on reaching global map destination

### ISSUE THREAD

**Issue by qDshun** [rwmt/Multiplayer#455]
Multiplayer 0.10.2
RimWorld 1.5.4085

Caravan disappears when trying to go into combat\tile (examples: Raid outpost with 2 psylink neuroformers)

**Comment by wjwwood** [comment]
I've encountered the same thing. It's just gone, no notice of caravan lost or anything like that. Is there some other debugging information I could provide?

**Comment by PSR2144-3933** [comment]
i also encountered this problem. a temporary solution i found is that, after several saves and loads, my caravan _can_ successfully enter that tile.

**Comment by UnknownNonameUser75B** [comment]
Want to pump up this issue. Played with friend in multiplayer with multifraction. All caravans sent to mission spots on global map are completely deleted from world on arrival with all stuff and crew of it. Impossible to complete any mission.

**Comment by Zetrith** [comment]
Fixed in 0.10.5
