### ISSUE TITLE
Desync when other player pushes the button "Create Caravan" 

### ISSUE THREAD

**Issue by abudzhel** [rwmt/Multiplayer#456]
Basically the description. Desync happens when other player pushes the button "Create Caravan". 
Should be easily reproducible, it happened every time with no exceptions. Should you need more information please let me know. 
Multiplayer 0.10.2
RimWorld 1.5.4085

**Comment by ltx111888** [comment]
确实，经常出现这种问题

**Comment by EZ64cool** [comment]
We've been able to work around this by creating a caravan hitching point and creating a caravan from there. 

That's in multi faction

**Comment by LeMatosDeFuk** [comment]
+1

**Comment by Infiexe** [comment]
+1

**Comment by Zetrith** [comment]
Fixed in 0.10.4
