### ISSUE TITLE
Desync on capture entity

### ISSUE THREAD

**Issue by Reese-D** [rwmt/Multiplayer#462]
If you play the anomaly mode with two players, you'll quickly encounter the first entity a sightseer. Upon clicking "Capture Sightseer" the game will desync. This seems to happen every time without fail, and should be easily reproduceable.

**Comment by SokyranTheDragon** [comment]
Should be fixed by #448.

Until then use the capture to specific building option, or draft pawn -> right click entity -> carry entity -> right click containment building -> place in specific containment.

**Comment by SokyranTheDragon** [comment]
The fix should be up on master branch already.
