### ISSUE TITLE
Desynchronization Related to Entity Health Changes

### ISSUE THREAD

**Issue by 1343008086** [rwmt/Multiplayer#465]
Thank you for supporting the RimWorld multiplayer mod. Here are some issues I encountered during gameplay. I have categorized these desynchronization reports based on my judgment to help you review them more effectively.

[NPCs and animals desynchronize when healthy.zip](https://github.com/rwmt/Multiplayer/files/15317179/NPCs.and.animals.desynchronize.when.healthy.zip)
[NPCs desynchronize during health changes and random inspirations.zip](https://github.com/rwmt/Multiplayer/files/15317181/NPCs.desynchronize.during.health.changes.and.random.inspirations.zip)
[NPCs desynchronize when bleeding.zip](https://github.com/rwmt/Multiplayer/files/15317182/NPCs.desynchronize.when.bleeding.zip)
[NPCs desynchronize when generating filth while moving and calculating disease probability.zip](https://github.com/rwmt/Multiplayer/files/15317183/NPCs.desynchronize.when.generating.filth.while.moving.and.calculating.disease.probability.zip)

**Comment by Zetrith** [comment]
This is quite a generic desync and you have a lot of mods. It's difficult to say what the issue is just based on the desync file and without more details.
