### ISSUE TITLE
Combat-Related Desynchronization

### ISSUE THREAD

**Issue by 1343008086** [rwmt/Multiplayer#467]
Thank you for supporting the RimWorld multiplayer mod. Here are some issues I encountered during gameplay. I have categorized these desynchronization reports based on my judgment to help you review them more effectively.

[Desynchronization occurs during battles with Diabolus and MechWarqueen.zip](https://github.com/rwmt/Multiplayer/files/15317284/Desynchronization.occurs.during.battles.with.Diabolus.and.MechWarqueen.zip)
[NPCs desynchronize when bullets are fired and hit entities during combat (this issue occurs frequently during battles with Diabolus, MechWarqueen, and Apocriton).zip](https://github.com/rwmt/Multiplayer/files/15317285/NPCs.desynchronize.when.bullets.are.fired.and.hit.entities.during.combat.this.issue.occurs.frequently.during.battles.with.Diabolus.MechWarqueen.and.Apocriton.zip)

**Comment by Zetrith** [comment]
This is quite a generic desync and you have a lot of mods. It's difficult to say what the issue is just based on the desync file and without more details.
