### ISSUE TITLE
Desynchronization Related to Entity Behavior Decisions and Events

### ISSUE THREAD

**Issue by 1343008086** [rwmt/Multiplayer#468]
Thank you for supporting the RimWorld multiplayer mod. Here are some issues I encountered during gameplay. I have categorized these desynchronization reports based on my judgment to help you review them more effectively

[NPC desynchronizes when being recruited.zip](https://github.com/rwmt/Multiplayer/files/15317322/NPC.desynchronizes.when.being.recruited.zip)
[NPC desynchronizes when making certain behavior decisions diverge.zip](https://github.com/rwmt/Multiplayer/files/15317324/NPC.desynchronizes.when.making.certain.behavior.decisions.diverge.zip)
[NPC desynchronizes when moving to destinations.zip](https://github.com/rwmt/Multiplayer/files/15317325/NPC.desynchronizes.when.moving.to.destinations.zip)
[NPC desynchronizes when social interactions are hindered by preventing drinking.zip](https://github.com/rwmt/Multiplayer/files/15317326/NPC.desynchronizes.when.social.interactions.are.hindered.by.preventing.drinking.zip)
[NPCs in VanillaFurnitureEC desynchronize when playing darts.zip](https://github.com/rwmt/Multiplayer/files/15317327/NPCs.in.VanillaFurnitureEC.desynchronize.when.playing.darts.zip)

**Comment by Zetrith** [comment]
This is quite a generic desync and you have a lot of mods. It's difficult to say what the issue is just based on the desync file and without more details.
