### ISSUE TITLE
Desync on the air conditioner and the caravan

### ISSUE THREAD

**Issue by dians1s** [rwmt/Multiplayer#478]
I play with a friend (with multifaction) without the rest of the mods, only harmony and multiplayer mod last version, desynchronization occurs when temperature is adjusted and after re-entry the temperature remains the same as it was originally (reset), then if I send a caravan to a friend or he starts sending, he again densychronizes me. The server is on it, the connection is perfect. Please fix this desync

**Comment by SokyranTheDragon** [comment]
Fixed by #472 and duplicate of #456
