### ISSUE TITLE
Game dysyncs every day at 6hr. All mods installed are max compatibility

### ISSUE THREAD

**Issue by SpartenNumber11** [rwmt/Multiplayer#484]
Playing on the new update with just one friend and the game is desyncing me every new day at exactly 6hr, we tried changing the auto save interval as that was what we thought was causing the issue, but it didn't stop me from still desyncing at 6hr.

**Comment by Rythyn** [comment]
I can confirm this. It's happening for me at 2am game time everyday, as that is when my auto save occurs.

**Comment by Zetrith** [comment]
Please give your mod lists and attach the desync files

**Comment by Zetrith** [comment]
Fixed in 0.10.5
