### ISSUE TITLE
Can't join game because "Mod data definitions differ"

### ISSUE THREAD

**Issue by BenjaminBossan** [rwmt/Multiplayer#511]
Thanks for this great mod. It worked quite well for a while but now I encountered a problem. I played multiplayer with a friend without issues but today, I suddenly can't join the game (same save file) anymore because

> Mod data definitions differ. They need to match before joining
ThingComp: Count_Diff
...

We did not change anything, mods are identical and in the same order. Files appear to differ but in the past I could just "fix and restart", or sometimes "connect anyway", but now, neither helps. Any idea what it could be?

More context, in case it matters:
- Only Ideology DLC
- Version 1.5.4297
- Friend hosts on Windows, I'm on Ubuntu
- It appears that there was a small Rimworld update today

Screenshots

![Screenshot from 2024-12-23 22-48-38](https://github.com/user-attachments/assets/7d668673-ef8e-47b3-bbfa-280a1f13c9be)
![Screenshot from 2024-12-23 22-49-52](https://github.com/user-attachments/assets/a0072332-ca6b-4f49-9800-60fd4715ddfc)

**Comment by notfood** [comment]
One of you have the mod Biomes! Core outdated. Both of you, unsubscribe, resubscribe.

**Comment by BenjaminBossan** [comment]
It worked, thanks.
