### ISSUE TITLE
When host desyncs (with arbiter/desync tracer enabled of course), Try Resync effectively does nothing

### ISSUE THREAD

**Issue by DBotThePony** [rwmt/Multiplayer#54]
Both 1.1 and current 1.0 versions are affected. After `Try resync` is selected, world is simulated (seemingly) successfully, but nothing happen after (for all connected players, including host). Child process (desync tracer) idle as if game was on pause.

**Comment by Linnun** [comment]
Can confirm. To elaborate, the game doesn't exactly end up paused, but in a frozen state that can not be unpaused anymore. The only thing left to do is to end the game or switch to singleplayer, and re-host a new session from there.

**Comment by notfood** [comment]
Long standing bug that happens when the host and the arbiter disagree on the first tick. A workaround is to disable the arbiter but know that you'll have a desync with other clients.

**Comment by NotherGithubAccount** [comment]
I've encountered this problem every time I tried resync, except once. This affected different kinds of desyncs, and the only time it worked there was no client connected. I don't know what would cause host and arbiter to disagree on the first tick, but it doesn't sound as if it is that common. You sure that's the cause?

**Comment by Zetrith** [comment]
Should be fixed in the latest beta.
