### ISSUE TITLE
Unfocusing game window when it load replay/autosave/simulate loaded save will pause the game

### ISSUE THREAD

**Issue by DBotThePony** [rwmt/Multiplayer#55]
To reproduce: Host a game from main menu and then unfocus the game. Notice that loading progress will not go any further until you focus the game again.
But after game was loaded and simulated unfocusing the game won't stop it.

*It is really annoying.*

**Comment by SweptWasTaken** [comment]
Could not replicate on Windows 10 in both Fullscreen and Windowed mode.

Tried unfocusing, clicking on my other monitor, minimizing, even sending Rimworld to another Desktop and it's still loading in the background. 

Maybe it's a hardware thing.

**Comment by rkost** [comment]
I have this issue too. Running arch linux with awesome wm and proprietary nvidia drivers. RimWorld is started natively (without proton). @DBotThePony are you on linux too? Maybe this is a linux thing?

**Comment by notfood** [comment]
I run Linux with nvidia and I can't reproduce.

**Comment by DBotThePony** [comment]
I run windows 10 w/ vega 56 and ryzen 7 1700x

**Comment by ZoeyVS** [comment]
This is likely due to a core Rimworld issue, you need to enable run in background else the game will pause when unfocused. 

Seeing as this is an old issue I'm going to assume this is the case and just close it, feel free to re-open if you can replicate with steps to do so.
