### ISSUE TITLE
Opening Comms Console triggers infinite windows

### ISSUE THREAD

**Issue by Nebual** [rwmt/Multiplayer#60]
Try opening comms with any faction to trade: the window opens infinitely (the sound loops), which effectively locks the game.

The same symptom, for the 'research completed' window, was fixed by https://github.com/rwmt/Multiplayer/commit/39e9c3addfb7d2f2e9e7bf750d38d996ee751673

In this save, there's a comms console in the bottom-left area of the base.
[replay-with-comms-console.zip](https://github.com/rwmt/Multiplayer/files/4496523/replay-with-comms-console.zip)

**Comment by Nebual** [comment]
Possibly related:

Trade tooltips throw an error
![error-getting-tip-text](https://user-images.githubusercontent.com/1627867/79638726-ee57b380-813b-11ea-8bf0-690d0d40b1ff.png)
![null-reference-exception-trade-tooltip](https://user-images.githubusercontent.com/1627867/79638728-f0217700-813b-11ea-8dbc-479b53536c02.png)

which suggests `TradeSession.trader` is null.

**Comment by notfood** [comment]
This has happened before, I fixed it this way last time:
https://github.com/rwmt/Multiplayer/commit/4b5b44fa4ec3fb181b0f409cd2851059ec857d25
