### ISSUE TITLE
No multiplayer button in GOG Rimworld

### ISSUE THREAD

**Issue by aleixlogin** [rwmt/Multiplayer#66]
Harmony and the multiplayer mod seem to be well installed and working, no error appears, but the Multiplayer button does not appear either.

<img width="960" alt="Rimworld_Mods" src="https://user-images.githubusercontent.com/5947876/79769655-afd51b00-832c-11ea-815e-6379a949a6f3.png">
<img width="960" alt="Rimworld_main" src="https://user-images.githubusercontent.com/5947876/79769659-b1064800-832c-11ea-9d6f-5c2ccd87b8d0.png">

**Comment by Parexy** [comment]
You should really go to our discord server for stuff like this since that is where we provide support from. https://discord.gg/S4bxXpv. Both because of live feedback but also because i have more questions like that you are using a bit older version of rimworld and what exact build of the mp mod you are using.

**Comment by SweptWasTaken** [comment]
> You should really go to our discord server for stuff like this since that is where we provide support from. https://discord.gg/S4bxXpv. Both because of live feedback but also because i have more questions like why you are using a bit older version of rimworld and what exact build of the mp mod you are using.

It isn't a legit version of Rimworld and I can't replicate it so i'm gonna close it as it's a misleading bug. I don't think this is even the GOG version...

**Comment by aleixlogin** [comment]
Sorry for not reporting back, but it now works with the latest version of the mod and rimworld. Anyway, in case you want to reproduce it, it was with a legitimate version of GOG, specifically from 20 days ago with the version **1.1.2604 rev 554** in combination with the release **v0.5.0.17** of the mod.

Thanks for the work with the mod.
![Screenshot_21](https://user-images.githubusercontent.com/5947876/80991747-c5703780-8e38-11ea-877c-4859dd4493ba.png)
