### ISSUE TITLE
Desync while casting pulse abilities

### ISSUE THREAD

**Issue by ZergerZ** [rwmt/Multiplayer#68]
Multiplayer game with 3 players.

De sync guaranteed to happen if one of the following pulse abilities is used:

Blinding Pulse
Berserk Pulse
Vertigo Pulse

After de-sync the host need to re host the game since clients will not be able to re sync on their own.

Tested with:
Rimworld Version: RimWorld v1.1.2610
Multiplayer version: v0.5.0.22

P.S. LOVE your mod !!!!!

**Comment by Nebual** [comment]
Beta14 in the Discord's #test-builds should fix at least Vertigo and possibly the others, though there is a report of Burden desyncing https://discordapp.com/channels/524286515644203028/702190105607143424/703312969051799656 so more testing of abilities is due.

**Comment by ZergerZ** [comment]
Burden ability was used multiple times and so far no de-sync on the usage

**Comment by ZergerZ** [comment]
Previously problematic pulse abilities were tested and no longer cause de-sync.
Thanks!
