### ISSUE TITLE
Desyncs when Traders/Raiders Arrive (unsure how to reproduce)

### ISSUE THREAD

**Issue by Nebual** [rwmt/Multiplayer#69]
There have been several reports as of 1.1 of desyncs when Traders/Raiders arrive, though its unclear exactly why, as most don't experience that.

It may be related to 'Pause on Events' having a different setting between clients. That, along with some other settings like Pause on Load and Run in Background are _supposed_ to be forced to specific values when Multiplayer is active, but those patches seem to be inconsistently working in 1.1...

**Comment by NotherGithubAccount** [comment]
Just to confirm, I often see desyncs when traders are around. I thought it was related to the actual trading part, but that may be a red herring.

**Comment by Synaps3** [comment]
We also commonly desync when raids arrive. The resulting raiders can have different names, loadouts, and map entry locations as seen by desync'd clients.  For example entering on the south of the map with mostly shotguns vs entering on the north of the map with rifles.

The desync is instant upon raid occurrance, and at least in the most recent experience was noticed by the host machine and not the clients.

**Comment by Zetrith** [comment]
Stale issue, can't reproduce
