### ISSUE TITLE
Desync on Royal Favor recipient selection after quest completion.

### ISSUE THREAD

**Issue by ZergerZ** [rwmt/Multiplayer#78]
De sync happens after selecting recipient of the royal favor on quest completion.

Tested with 
Multiplayer: v0.5.0.25
Rimworld: 1.1.2618 & 1.1.2610

**Comment by Nebual** [comment]
Can you attach a save prior to the selection?

**Comment by skiv1102** [comment]
I have the same problem
game version: 1.1.2604
Multiplayer: 0.5.0.22
Here the multiplayer save and desync info archive
[save25.zip](https://github.com/rwmt/Multiplayer/files/4573240/save25.zip)
[Desync-31.zip](https://github.com/rwmt/Multiplayer/files/4573242/Desync-31.zip)

**Comment by ZergerZ** [comment]
Thanks :D unfortunately I've lost that save file

**Comment by notfood** [comment]
It's been fixed.
