### ISSUE TITLE
Desync on the "Speech form the Throne"

### ISSUE THREAD

**Issue by ZergerZ** [rwmt/Multiplayer#85]
Multiplayer game with 3 players.

When host activates the ability both clients will be de-synced.

If one of the clients tries to use the ability nothing happens and the client is getting de-sync.

Tested with
Multiplayer: v0.5.0.25
Rimworld: 1.1.2618 & 1.1.2610

**Comment by PhoenixICE** [comment]
This is fixed in the unstable/dev branch - https://github.com/rwmt/Multiplayer/commit/4e186c45d5fecb2e45ead5fefaa6bcb78cd21796
