### ISSUE TITLE
Giving speech seems to desync the game.

### ISSUE THREAD

**Issue by mightyhuhn** [rwmt/Multiplayer#89]
i wanted to ask other user in the discord before but after searching for like 30 mins for a green checkmark (what ever that may be) i have to go this way.

every time i used the royal feature giving a speech the game desynced. the game is modded so it would be much better if i could ask other user first if they have the same problem but it is as it is.

i have more stuff like rimatomic shouldn't be a "4" because the liberator doesn't work in multiplayer it's complaining that the scas isn't manned even if it's manned.

**Comment by notfood** [comment]
Self cast is fixed in Dev branch with https://github.com/rwmt/Multiplayer/commit/cdcde88178e91a829b0028cbafb576b7c364084b

**Comment by mightyhuhn** [comment]
thanks
