### ISSUE TITLE
Ability to have multiple teams/factions

### ISSUE THREAD

**Issue by RagingFlames** [rwmt/Multiplayer#9]
The ability to split off and not work co-operatively would be much appreciated. Some major problems with "just pretending" right now is that your pawns are effected by moods that have nothing to do with your settlement. Take for example, I was playing a game with 3 friends all on separate tiles. One person started an organ harvesting op, and everyone was punished for it. So if it isn't possible to have different factions, it would be nice to not have these debuffs be applied to pawns on every tile.

**Comment by olivercool103** [comment]
Yes, please! Starting in different factions would be total sense!

**Comment by MaverickMartyn** [comment]
Hey there.
I'm interested in attempting to implement this.
I haven't had time to look at the code yet, but I am experienced in C#.
Do you guys have any pointers to get me started, and help speed up the process?
Thanks. :)

**Comment by olivercool103** [comment]
I'd pay for this update.

**Comment by daerogami** [comment]
Wouldn't this be a fundamental issue with how RimWorld is implemented?

Each client would have to generate as a separate faction and the director may still trigger events on behalf of that faction.
I imagine this would be a substantially different implementation of multiplayer.

As I understand it, the current multiplayer is an illusion. There is only one 'player' just providing input from one-or-more clients. Therefore, no core game-play behavior has to change, just be kept in sync. The biggest amount of work I imagine would be instancing other client's pawns/maps/over world tokens and keeping all of that out of the director's influence (prevent it from spawning events on your behalf and the AI taking over when on a player's map causing desync).

Much of the above is supposition, someone more familiar with the intricacies of RimWorld and this mod feel free to correct me.

**Comment by Agaros007** [comment]
you mean you looking for something like this?: https://github.com/pardeike/RimBattle

**Comment by Zetrith** [comment]
Multifaction is now in beta

https://rimworldmultiplayer.com/post/23_10_18_multifaction/
