### ISSUE TITLE
B

### ISSUE THREAD

**Issue by tmvegh** [rwmt/Multiplayer#93]
Mod broken by 1.1.2647 patch. Desyncs at random and 'Form Caravan' button disabled. Tested on fresh install; only harmony, core, royal, multi.

**Comment by notfood** [comment]
Caravans are working, please submit a proper issue. Your issue is too vague. You offer no save, you offer no screenshots, no steps to reproduce. "It's broken!" is not an issue report.

**Comment by tmvegh** [comment]
Sorry @notfood ; I should know better. I have attached the debug log, the save, and s screenshot of my mods.

Steps to reproduce:
Issue 1: Form Caravan CTA not working.
1) Start a new single-player game (in this example I'm using default crashlanded, Cassandra, strive, committed.
2) Click on 'World' and observe that the 'Form Caravan' CTA does not respond to clicks; other CTAs work fine.

When joined by a second player, desyncs were nearly constant. If/when I can get him online, I will attempt to get a save game file for that, if it would be beneficial.

[rimworld error.zip](https://github.com/rwmt/Multiplayer/files/4714084/rimworld.error.zip)

![image](https://user-images.githubusercontent.com/66188973/83467030-ccde2d00-a446-11ea-9d8a-72cf38bb45d4.png)

**Comment by notfood** [comment]
You're using 1-2-3 mods, it's not supported. Head to the discord for support.
