### ISSUE TITLE
0.5.1.0 Causes User Interface to dissapear

### ISSUE THREAD

**Issue by AzZotik** [rwmt/Multiplayer#95]
RimWorld 1.1.2647 Starting from the mods menu, only using the latest Harmony 2.0.1 and Multiplayer 0.5.1.0. Causes "Close" button to disappear when pressing on Multiplayer, attempt to create a colony even in singleplayer makes Storyteller menu to appear blank, loading existing save starts the game without any UI and empty small window in the middle. Debug log gets filled with the same exception multiple times during that.
![1](https://user-images.githubusercontent.com/45207513/83866902-2f7a4600-a731-11ea-87d5-b84c8fb517e0.png)
![2](https://user-images.githubusercontent.com/45207513/83866942-3d2fcb80-a731-11ea-896c-77157bbaccf5.PNG)
![3](https://user-images.githubusercontent.com/45207513/83866950-3ef98f00-a731-11ea-87fd-3962861da169.PNG)

**Comment by notfood** [comment]
0.5.1.0 does not support 1.1.2647, it's specifically for 1.1.2654
