### ISSUE TITLE
Anything involving forming a caravan results in a desync loop

### ISSUE THREAD

**Issue by SmokePuddingEveryday** [rwmt/Multiplayer#96]
I'm having an issue where the client seems to desync anytime a caravan from the initial base is formed. This happens on both regular time and async mode enabled and I can't figure out a way to fix the Rimworld instance (not even restarting), as every time a resync attempt occurs / the world tries to load again, the pawn is sent back on the caravan and the desync occurs again (pawns don't register as travelling in a caravan on host / client, depending on who settled it.) It doesn't matter what tile is being selected to travel to. If I manage to get both clients synced with an idle caravan on the world map by hosting the server after setting the caravan, if the host sets a destination for the caravan to travel to, the caravan doesn't register it on the client and a desync occurs instantly.

The only way to fix the issue is to restart the game on both client and host I believe.

There are no mods enabled other than Harmony and Multiplayer on both machines. Config files are all synced. Host in on Steam and Client is on GOG (but the error still occurs the other way around.) Host using the latest Workshop file, and GOG is using the latest Github download. Files were also reinstalled.

The client either gets hit with one of these three:

`Random state from commands doesn't match`
`wrong random state on map 0 `
`Map instnaces don't match` (<-- this one happens when a caravan settles on a tile in the world. The area is settled but the client gets the desync which begins the desync loop.)

This happens 100% of the time under the same circumstances. I've tested on about 5 different worlds.

Problem is similar to the one this Discord user was having, except my game fails to catch up after the desync: https://discordapp.com/channels/524286515644203028/702190105607143424/717033695994970162

[Caravan_Desync_Host.zip](https://github.com/rwmt/Multiplayer/files/4762379/Caravan_Desync_Host.zip)
[Caravan_Desync_Client.zip](https://github.com/rwmt/Multiplayer/files/4762380/Caravan_Desync_Client.zip)

**Comment by notfood** [comment]
I'm certain your files don't match. This can happen on pure vanilla due to steam messing up the files, keeping old ones around. The fix is to delete the `Data` folder and revalidate for both host and clients.
